---
title: "CodeHover Template"
autor: "Your Name"
output: 
  html_document:
    css: ["CodeHoverStyle.css"]
    includes:
      after_body: CodeHoverJavascript.txt
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
library(tidyverse)
library(htmltools)
library(knitr)
library(CodeHover)

```


# 1) Create a table using **ch_int()**, **ch_row()**, and **ch_out()**.

In this example we already have saved images for every step in the **IMG** folder

```{r, echo=TRUE}
result <- ch_int(type = "incremental", css_class = "teste") %>% 
          ch_row(text = 
                     "ggplot() + 
                      <br> <tab1> geom_point(data = cars, </tab1>
                      <br> <tab2> aes(x = speed, </tab2>
                      <br> <tab2> &nbsp; &nbsp; y = dist, </tab2>",
                   img ="./IMG/1b.png") %>% 
          ch_row(text = "<tab2> color = 'red')) + </tab2>",
                   img ="./IMG/2b.png") %>%   
          ch_row(text = "<tab1> scale_y_continuous(limits = c(0,100)) + </tab1>",
                   img ="./IMG/3b.png") %>% 
          ch_row(text = "<tab1> labs(title = 'A ggplot fot the rest of us', </tab1>",
                   img ="./IMG/4b.png") %>%   
          ch_row(text = "<tab2> subtitle = 'Testing a way of explicit showing the R workflow') + </tab2>",
                   img ="./IMG/5b.png") %>% 
          ch_row(text = "<tab1>  theme_bw()</tab1> ",
                   img ="./IMG/6b.png") %>%
          ch_out(img_holder = "./IMG/1b.png") 
  
```

# 2) Call the table into the HTML with {htmltools}.

```{r, echo=TRUE}
htmltools::HTML(result)

```

